/** @type {import("prettier").Config} */
const config = {
    printWidth: 120,
    proseWrap: 'never',
    arrowParens: 'always',
    endOfLine: 'lf',
    trailingComma: 'es5',
    tabWidth: 4,
    singleQuote: true,
    overrides: [
        {
            files: ['**/*.css', '**/*.html', '**/*.svg'],
            options: {
                singleQuote: false,
            },
        },
    ],
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
    importOrder: [
        '<TYPES>(react)',
        '<TYPES>(next)',
        '<TYPES>',
        '<TYPES>^@/',
        '<TYPES>^[./]',
        '^react$',
        '^react-dom',
        '^next',
        '<BUILTIN_MODULES>',
        '<THIRD_PARTY_MODULES>',
        '^@/lib',
        '^(@/lib/constants|@/lib/schemas|@/lib/regexps|@/lib/utils)(/.*)$',
        '^(@/hooks|@/providers)(/.*)$',
        '^@/services',
        '^@/modules',
        '^@/components',
        '^@/components/layouts',
        '^@/components/ui',
        '^@/icons',
        '^[./].*/constants',
        '^[./].*/regexes',
        '^[./].*/schemas',
        '^[./].*/api',
        '^[./].*/hooks',
        '^[./].*/providers',
        '^[./].*/utils',
        '^[./].*/components',
        '^[./]',
        '\\.css$',
        '^[./].*/public/',
    ],
    importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
    importOrderTypeScriptVersion: '5.0.0',
};

export default config;
