name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npx netlify build
        env:
          NETLIFY_AUTH_TOKEN: nfp_UU6W9DhfHLUwus18JgufmsK1YCAA4XV3dc94
          NETLIFY_SITE_ID: d298c47b-5aa1-4b9a-a603-9684f2f3ce37
          MONGODB_URI: mongodb+srv://navhigh_db_user:BjEA93E0R02G2SNp@cluster0.no8wtn1.mongodb.net/?appName=Cluster0
          NEXT_PUBLIC_API_URL: http://localhost:3000

      - name: Deploy to Netlify
        run: npx netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: nfp_UU6W9DhfHLUwus18JgufmsK1YCAA4XV3dc94
          NETLIFY_SITE_ID: d298c47b-5aa1-4b9a-a603-9684f2f3ce37
          MONGODB_URI: mongodb+srv://navhigh_db_user:BjEA93E0R02G2SNp@cluster0.no8wtn1.mongodb.net/?appName=Cluster0
          NEXT_PUBLIC_API_URL: http://localhost:3000
